project_name: hystrix_exporter
release:
  github:
    owner: ContaAzul
    name: hystrix_exporter
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archive:
  name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
  files:
  - config.yml
changelog:
  filters:
    exclude:
    - '^Merge (remote|branch|pull)'
dockers:
- image: caninjas/hystrix_exporter
  extra_files:
  - config.yml
  tag_templates:
  - '{{ .Tag }}'
  - 'v{{ .Major }}'
  - 'v{{ .Major }}.{{ .Minor }}'
  - latest
