project_name: hystrix_exporter
release:
  github:
    owner: mdavydau
    name: hystrix_exporter
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
archive:
  files:
  - config.yml
dockers:
- image: caninjas/hystrix_exporter
  latest: true
  extra_files:
  - config.yml
